name: Say Hello

on:
  push:
    branches:
      - main

jobs:
    hello_word:
        runs-on: ubuntu-22.04
        steps:
          - name: Echo the message
            run: |
                echo "Hola Rafael Guevara Aller"
          - name: Dime la fecha
            run: date
          - run: ls -l

