name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencias
        run: npm install
      - name: Lint
        run: npm run eslint
        shell: /usr/bin/bash -e {0}